package(default_visibility = ["//rtp_llm:__subpackages__", "//internal_source:__subpackages__"])

py_library(
    name = "test_util",
    srcs = glob(["*.py"]),
    deps = [
        "//rtp_llm:testlib"
    ]
)