# 基础镜像的Dockerfile ： https://lark.alipay.com/aone/docker/rm2g1d
# 基于基础镜像
FROM reg.docker.alibaba-inc.com/alibase/alios7u2-min

# 指定应用名字，配置在$APP_NAME.release文件里
# 从 build.tools.docker.args=--build-arg APP_NAME=${APP_NAME} 传入
ARG APP_NAME
ENV APP_NAME=${APP_NAME}
# 增加jdk路径
ENV PATH "$PATH:/opt/taobao/java/bin/"
#容器启动时自动执行的脚本，我们一般会将应用启动脚本放在这里，相当于系统自启应用

# 将应用启动脚本和配置文件复制到镜像中
COPY environment/common/bin/ /home/admin/${APP_NAME}/bin

# 构建时要做的事，一般是执行shell命令，例如用来安装必要软件，创建文件（夹），修改文件
RUN rpm -ivh --nodeps "http://yum.tbsite.net/taobao/7/x86_64/current/ajdk21/ajdk21-21.0.6.0.6-20250508143732.alios7.x86_64.rpm" && \
rpm -ivh --nodeps "http://yum.tbsite.net/taobao/7/x86_64/current/tengine-proxy/tengine-proxy-2.1.13-20170802132414.el7u2.x86_64.rpm" && \
rpm -ivh --nodeps "http://yum.tbsite.net/alios/7/os/x86_64/Packages/taobao-cronolog-1.6.2-15.alios7.x86_64.rpm" && \
mkdir -p /home/admin/$APP_NAME/target && \
echo "/home/admin/$APP_NAME/bin/appctl.sh stop" > /home/admin/stop.sh && \
echo "/home/admin/$APP_NAME/bin/appctl.sh restart" >> /home/admin/start.sh && \
echo "/home/admin/$APP_NAME/bin/preload.sh" > /home/admin/health.sh && \
cp /home/admin/$APP_NAME/bin/prestop.sh /home/admin/prestop.sh && \
cp /home/admin/$APP_NAME/bin/whale_start.sh /home/admin/whale_start.sh && \
mkdir -p /etc/ilogtail/users && \
mkdir -p /etc/uniagent/users && \
touch /etc/ilogtail/users/1577156732608266 && \
chmod +x /home/admin/*.sh

# 将应用nginx脚本复制到镜像中
COPY environment/common/cai/ /home/admin/cai/

# 设置文件操作权限
RUN chmod -R a+x /home/admin/${APP_NAME}/bin/ /home/admin/cai/bin/ && mkdir -p /logs/eagleeye && chmod -R a+xw /logs

# 挂载数据卷,指定目录挂载到宿主机上面,为了能够保存（持久化）数据以及共享容器间的数据，为了实现数据共享，例如日志文件共享到宿主机或容器间共享数据.
VOLUME /home/admin/$APP_NAME/logs \
       /home/admin/logs \
       /home/admin/cai/logs \
       /home/admin/diamond \
       /logs/eagleeye

# 启动容器时进入的工作目录
WORKDIR /home/admin/$APP_NAME/bin

# 将构建出的主包复制到指定镜像目录中
#以下内容为集团安全部应用安全能力中心自动修复添加，用于静态部署RASP
COPY environment/common/bin/RASP.sh /home/admin
ENTRYPOINT ["source /home/admin/RASP.sh start && /home/admin/start.sh"]
