FROM hub.docker.alibaba-inc.com/aone/flexlb_base_arm64:2026_07_31_16_30_39f8ce0_arm64

ARG APP_NAME=ai-whale
ENV APP_NAME=${APP_NAME}
ENV SKIP_CHECK_STATUS_TAOBAO=true
ENV NGINX_SKIP=1

RUN echo whale_wave_prod > /etc/ilogtail/user_defined_id && \
    echo whale_wave_prod > /etc/uniagent/user_defined_id

COPY environment/common/bin/RASP.sh /home/admin/RASP.sh
COPY ${APP_NAME}.tgz /home/admin/${APP_NAME}/target/${APP_NAME}.tgz

ENTRYPOINT ["/bin/bash", "-lc", "source /home/admin/RASP.sh start && exec /home/admin/start.sh"]
