ARG FROM_IMAGE
FROM ${FROM_IMAGE}

ARG APP_NAME=ai-whale
ENV APP_NAME=${APP_NAME}
ENV SERVICE_OPTS="${SERVICE_OPTS} -Dspring.profiles.active=online"
ENV SKIP_CHECK_STATUS_TAOBAO=true
ENV NGINX_SKIP=1

RUN echo whale_wave_prod > /etc/ilogtail/user_defined_id && \
    echo whale_wave_prod > /etc/uniagent/user_defined_id

COPY environment/common/bin/RASP.sh /home/admin/RASP.sh
COPY ${APP_NAME}.tgz /home/admin/${APP_NAME}/target/${APP_NAME}.tgz

ENTRYPOINT ["/bin/bash", "-lc", "source /home/admin/RASP.sh start && exec /home/admin/start.sh"]
