FROM hub.docker.alibaba-inc.com/aone-base-global/flexlb_base:20260519160456544448

############# production #################
# 由于金山云bridge_vpc无法访问公网，因此跳过check
ENV SKIP_CHECK_STATUS_TAOBAO="true"

RUN echo whale_wave_prod > /etc/ilogtail/user_defined_id && \
echo whale_wave_prod > /etc/uniagent/user_defined_id


COPY environment/common/bin/ /home/admin/${APP_NAME}/bin/
RUN chmod +x /home/admin/${APP_NAME}/bin/*.sh
#以下内容为集团安全部应用安全能力中心自动修复添加，用于静态部署RASP
COPY environment/common/bin/RASP.sh /home/admin

ENTRYPOINT ["source /home/admin/RASP.sh start &&  /home/admin/start.sh"]
COPY ${APP_NAME}.tgz /home/admin/${APP_NAME}/target/${APP_NAME}.tgz
