FROM hub.docker.alibaba-inc.com/aone/flexlb_base:20260731163019908478

############# production #################
# 设置spring profile或者自定义的jvm参数。如果需要则打开下面的注释内容
# FLEXLB_ACTIVE_PROFILES 可在部署时通过环境变量覆盖（如 online,dashscope）；
# appctl.sh 使用 eval 启动 java，运行时才展开 ${FLEXLB_ACTIVE_PROFILES}
ENV FLEXLB_ACTIVE_PROFILES=online
ENV SERVICE_OPTS="${SERVICE_OPTS} -Dspring.profiles.active=\${FLEXLB_ACTIVE_PROFILES}"
# 由于金山云bridge_vpc无法访问公网，因此跳过check
ENV SKIP_CHECK_STATUS_TAOBAO="true"

RUN echo whale_wave_prod > /etc/ilogtail/user_defined_id && \
echo whale_wave_prod > /etc/uniagent/user_defined_id


#以下内容为集团安全部应用安全能力中心自动修复添加，用于静态部署RASP
COPY environment/common/bin/RASP.sh /home/admin

ENTRYPOINT ["source /home/admin/RASP.sh start &&  /home/admin/start.sh"]
COPY ${APP_NAME}.tgz /home/admin/${APP_NAME}/target/${APP_NAME}.tgz
