py_test(
    name = "test_deepseek_newloader",
    srcs = ["test_deepseek_newloader.py"],
    deps = [
        "//rtp_llm:torch",
        "//rtp_llm/models_py:new_weight_loader",
        "//rtp_llm/models_py/standalone:py_standalone_testlib",
    ],
)
