py_test(
    name = "timeline_test",
    srcs = ["timeline_test.py"],
    deps = [
        "//rtp_llm/models_py:modules",
        "//rtp_llm:testlib",
    ],
)

py_test(
    name = "quantized_linear_import_test",
    srcs = ["quantized_linear_import_test.py"],
    deps = [
        "//rtp_llm/models_py:modules",
        "//rtp_llm:testlib",
    ],
)

py_test(
    name = "shared_expert_test",
    srcs = ["shared_expert_test.py"],
    deps = [
        "//rtp_llm/models_py:modules",
        "//rtp_llm:testlib",
    ],
)

py_test(
    name = "fp8_fp4_layer_test",
    srcs = ["fp8_fp4_layer_test.py"],
    deps = [
        "//rtp_llm/models_py:modules",
        "//rtp_llm:testlib",
    ],
)
