#!/bin/sh
command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nnot found git-lfs, If you no longer wish to use git-lfs, remove this hook by deleting .githooks/post-commit.\n"; exit 2; }
git lfs post-commit "$@"
