package(default_visibility = ["//rtp_llm:__subpackages__", "//internal_source:__subpackages__"])

py_library(
    name = "loader",
    srcs = glob([
        "*.py",
    ]),
    deps = [
        "//rtp_llm:utils",
    ]
)