# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rtp_llm/multimodal/kvcm/lookup.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n$rtp_llm/multimodal/kvcm/lookup.proto\x12\x1ertp_llm.multimodal.kvcm.lookup"\'\n\x06Status\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t"k\n\x06Header\x12\x36\n\x06status\x18\x01 \x01(\x0b\x32&.rtp_llm.multimodal.kvcm.lookup.Status\x12\x12\n\nrequest_id\x18\x02 \x01(\t\x12\x15\n\rtracer_result\x18\x03 \x01(\t")\n\x0cLocationSpec\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03uri\x18\x02 \x01(\t"\x8a\x01\n\rValueLocation\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x11\n\tspec_size\x18\x02 \x01(\x05\x12\x44\n\x0elocation_specs\x18\x03 \x03(\x0b\x32,.rtp_llm.multimodal.kvcm.lookup.LocationSpec\x12\x12\n\nvalue_size\x18\x04 \x01(\x04"\x19\n\x07KeyMask\x12\x0e\n\x06values\x18\x01 \x03(\x08"U\n\nGetRequest\x12\x10\n\x08trace_id\x18\x01 \x01(\t\x12\x13\n\x0binstance_id\x18\x02 \x01(\t\x12\x12\n\nquery_type\x18\x03 \x01(\x05\x12\x0c\n\x04keys\x18\x04 \x03(\t"\xc2\x01\n\x0bGetResponse\x12\x36\n\x06header\x18\x01 \x01(\x0b\x32&.rtp_llm.multimodal.kvcm.lookup.Header\x12@\n\tlocations\x18\x02 \x03(\x0b\x32-.rtp_llm.multimodal.kvcm.lookup.ValueLocation\x12\x39\n\x08hit_mask\x18\x03 \x01(\x0b\x32\'.rtp_llm.multimodal.kvcm.lookup.KeyMaskb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "rtp_llm.multimodal.kvcm.lookup_pb2", _globals
)
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _globals["_STATUS"]._serialized_start = 72
    _globals["_STATUS"]._serialized_end = 111
    _globals["_HEADER"]._serialized_start = 113
    _globals["_HEADER"]._serialized_end = 220
    _globals["_LOCATIONSPEC"]._serialized_start = 222
    _globals["_LOCATIONSPEC"]._serialized_end = 263
    _globals["_VALUELOCATION"]._serialized_start = 266
    _globals["_VALUELOCATION"]._serialized_end = 404
    _globals["_KEYMASK"]._serialized_start = 406
    _globals["_KEYMASK"]._serialized_end = 431
    _globals["_GETREQUEST"]._serialized_start = 433
    _globals["_GETREQUEST"]._serialized_end = 518
    _globals["_GETRESPONSE"]._serialized_start = 521
    _globals["_GETRESPONSE"]._serialized_end = 715
# @@protoc_insertion_point(module_scope)
