load("//:def.bzl", "copts")
load("@rtp_llm//bazel:defs.bzl", "torch_deps")

cc_library(
    name = "weights_define",
    hdrs = [
        "W.h",
        "Weights.h",
    ],
    deps = [
    ],
    visibility = ["//visibility:public"],
)
