py_test(
    name = "test_qwen2_dense_load",
    srcs = ["test_qwen2_dense_load.py"],
    deps = [
        "//rtp_llm:numpy",
        "//rtp_llm:safetensors",
        "//rtp_llm:torch",
        "//rtp_llm/models_py:new_weight_loader",
    ],
)
