
py_test(
    name = "test",
    srcs = [
        "test.py",
    ],
    data = [
    ],
    deps = [
        "//maga_transformer:testlib",
    ],
    env = {
        "MODEL_TYPE": "qwen2",
        "CHECKPOINT_PATH": "Qwen/Qwen-1_8B-Chat",
    }
)
