from __future__ import annotations

import asyncio
from typing import Any, Protocol

from rtp_llm.kv_cache_subscriber.models import CacheSnapshot


class CacheStatusSource(Protocol):
    async def fetch_snapshot(self) -> CacheSnapshot:
        """Return a complete cache view or raise without returning partial data."""

    async def close(self) -> None:
        """Release transport resources."""


class RtpGrpcCacheStatusSource:
    """Fetch and merge full ``GetCacheStatus`` responses from RTP DP workers."""

    def __init__(self, endpoints: tuple[str, ...], timeout_s: float) -> None:
        if not endpoints:
            raise ValueError("at least one RTP gRPC endpoint is required")
        if timeout_s <= 0:
            raise ValueError("timeout_s must be > 0")

        # These files are generated by RTP-LLM's existing model_rpc proto build.
        # Keep imports lazy so the diff state machine remains testable without a
        # built RTP runtime tree.
        import grpc
        import rtp_llm.cpp.model_rpc.proto.model_rpc_service_pb2 as pb2
        from rtp_llm.cpp.model_rpc.proto.model_rpc_service_pb2_grpc import (
            RpcServiceStub,
        )

        self._grpc = grpc
        self._pb2 = pb2
        self._stub_type = RpcServiceStub
        self._endpoints = endpoints
        self._timeout_s = timeout_s
        self._channels: list[Any] = []
        self._stubs: list[Any] = []

    def _ensure_connections(self) -> None:
        if self._stubs:
            return
        # grpc.aio channels bind to the active event loop. Create them lazily
        # from fetch_snapshot(), after asyncio.run() has installed that loop.
        for endpoint in self._endpoints:
            channel = self._grpc.aio.insecure_channel(
                endpoint,
                options=[("grpc.max_receive_message_length", 256 * 1024 * 1024)],
            )
            self._channels.append(channel)
            self._stubs.append(self._stub_type(channel))

    async def _fetch_one(self, stub: Any) -> Any:
        request = self._pb2.CacheVersionPB(
            latest_cache_version=-1,
            need_cache_keys=True,
        )
        return await stub.GetCacheStatus(request, timeout=self._timeout_s)

    async def fetch_snapshot(self) -> CacheSnapshot:
        # Requiring every endpoint to succeed prevents a temporarily missing DP
        # response from being interpreted as mass cache eviction.
        self._ensure_connections()
        responses = await asyncio.gather(*(self._fetch_one(stub) for stub in self._stubs))
        block_sizes = {int(response.block_size) for response in responses}
        if len(block_sizes) != 1:
            raise RuntimeError(
                f"RTP workers returned inconsistent block sizes: {sorted(block_sizes)}"
            )

        keys: set[int] = set()
        versions: list[int] = []
        for response in responses:
            keys.update(int(key) for key, present in response.cache_keys.items() if present)
            versions.append(int(response.version))

        # Version is observability only. RTP's memory-cache keys are not covered
        # by SharedBlockCache::version(), so callers must always diff full keys.
        version = min(versions) if versions else -1
        return CacheSnapshot(
            keys=frozenset(keys),
            block_size=block_sizes.pop(),
            version=version,
        )

    async def close(self) -> None:
        await asyncio.gather(*(channel.close() for channel in self._channels))
