#include <gtest/gtest.h>
#include <cuda_runtime.h>
#include <torch/torch.h>
#include <vector>

#include "rtp_llm/models_py/bindings/cuda/kernels/speculative_sampling/sampling.h"
#include "rtp_llm/models_py/bindings/cuda/kernels/speculative_sampling/gumbel_sampling.h"
#include "rtp_llm/models_py/bindings/common/kernels/vocab_prune/mapping.h"

class SpeculativeSamplingKernelTest: public ::testing::Test {
protected:
    void SetUp() override {
        ASSERT_EQ(cudaStreamCreate(&stream_), cudaSuccess);
    }

    void TearDown() override {
        cudaStreamDestroy(stream_);
    }

    cudaStream_t stream_ = nullptr;

    static torch::TensorOptions floatCuda() {
        return torch::TensorOptions(torch::kFloat32).device(torch::kCUDA);
    }
    static torch::TensorOptions intCuda() {
        return torch::TensorOptions(torch::kInt32).device(torch::kCUDA);
    }
    static torch::TensorOptions int64Cuda() {
        return torch::TensorOptions(torch::kInt64).device(torch::kCUDA);
    }
    static torch::TensorOptions boolCuda() {
        return torch::TensorOptions(torch::kBool).device(torch::kCUDA);
    }
};

// These IDs are generated by vLLM's v1/worker/gpu/sample/gumbel.py.  The
// deterministic integer-built logits make this a direct compatibility probe
// for the two-stage (seed, absolute-position) Philox key and flipped-fp32
// Gumbel transform, rather than merely a replay test of our own kernel.
TEST_F(SpeculativeSamplingKernelTest, GumbelSample_MatchesVllmGolden) {
    constexpr int64_t rows       = 6;
    constexpr int64_t vocab_size = 4099;
    auto row = torch::arange(rows, int64Cuda()).view({rows, 1});
    auto col = torch::arange(vocab_size, int64Cuda()).view({1, vocab_size});
    auto logits = torch::remainder(row * 131 + col * 17, 257).to(torch::kFloat32) / 37.0F - 3.0F;
    auto seeds = torch::tensor(std::vector<int64_t>{0, 1, 42, 2147483647, 20260731, 987654321}, int64Cuda());
    auto positions = torch::tensor(std::vector<int64_t>{0, 1, 17, 1024, 65537, 999999}, int64Cuda());
    auto temperatures = torch::tensor({0.0F, 1.0F, 0.5F, 1.5F, 0.8F, 1.0F}, floatCuda());

    auto sampled = rtp_llm::gumbelSample(logits, seeds, positions, temperatures, false, true);
    auto expected = torch::tensor(std::vector<int64_t>{136, 187, 3883, 1609, 982, 610}, int64Cuda());
    EXPECT_TRUE(torch::equal(sampled, expected));

    auto shifted = rtp_llm::gumbelSample(logits, seeds, positions + 1, temperatures, false, true);
    auto shifted_expected = torch::tensor(std::vector<int64_t>{136, 2894, 967, 2162, 1826, 2541}, int64Cuda());
    EXPECT_TRUE(torch::equal(shifted, shifted_expected));
}

TEST_F(SpeculativeSamplingKernelTest, GumbelSampleFp64_MatchesVllmGolden) {
    constexpr int64_t rows       = 6;
    constexpr int64_t vocab_size = 4099;
    auto row = torch::arange(rows, int64Cuda()).view({rows, 1});
    auto col = torch::arange(vocab_size, int64Cuda()).view({1, vocab_size});
    auto logits = torch::remainder(row * 131 + col * 17, 257).to(torch::kFloat32) / 37.0F - 3.0F;
    auto seeds = torch::tensor(std::vector<int64_t>{0, 1, 42, 2147483647, 20260731, 987654321}, int64Cuda());
    auto positions = torch::tensor(std::vector<int64_t>{0, 1, 17, 1024, 65537, 999999}, int64Cuda());
    auto temperatures = torch::tensor({0.0F, 1.0F, 0.5F, 1.5F, 0.8F, 1.0F}, floatCuda());

    auto sampled = rtp_llm::gumbelSample(logits, seeds, positions, temperatures, false, true, true);
    auto expected = torch::tensor(std::vector<int64_t>{136, 157, 2236, 2413, 3702, 339}, int64Cuda());
    EXPECT_TRUE(torch::equal(sampled, expected));

    auto shifted = rtp_llm::gumbelSample(logits, seeds, positions + 1, temperatures, false, true, true);
    auto shifted_expected = torch::tensor(std::vector<int64_t>{136, 3741, 2025, 1086, 164, 2087}, int64Cuda());
    EXPECT_TRUE(torch::equal(shifted, shifted_expected));
}

TEST_F(SpeculativeSamplingKernelTest, GumbelSample_RejectsEmptyBatchBeforeKernelLaunch) {
    auto logits = torch::empty({0, 16}, floatCuda());
    auto seeds = torch::empty({0}, int64Cuda());
    auto positions = torch::empty({0}, int64Cuda());
    auto temperatures = torch::empty({0}, floatCuda());

    EXPECT_THROW(
        rtp_llm::gumbelSample(logits, seeds, positions, temperatures, false, true),
        c10::Error);
}

TEST_F(SpeculativeSamplingKernelTest, GumbelSample_ProcessedProbabilitiesUseSameCoupling) {
    constexpr int64_t rows       = 6;
    constexpr int64_t vocab_size = 4099;
    auto row = torch::arange(rows, int64Cuda()).view({rows, 1});
    auto col = torch::arange(vocab_size, int64Cuda()).view({1, vocab_size});
    auto logits = torch::remainder(row * 131 + col * 17, 257).to(torch::kFloat32) / 37.0F - 3.0F;
    auto seeds = torch::tensor(std::vector<int64_t>{0, 1, 42, 2147483647, 20260731, 987654321}, int64Cuda());
    auto positions = torch::tensor(std::vector<int64_t>{0, 1, 17, 1024, 65537, 999999}, int64Cuda());
    auto temperatures = torch::tensor({0.0F, 1.0F, 0.5F, 1.5F, 0.8F, 1.0F}, floatCuda());
    auto temperature_divisor = torch::where(temperatures == 0.0F, torch::ones_like(temperatures), temperatures);
    auto probabilities = torch::softmax(logits / temperature_divisor.view({rows, 1}), -1);
    auto target_temperatures = torch::where(temperatures == 0.0F,
                                            torch::zeros_like(temperatures),
                                            torch::ones_like(temperatures));

    auto from_logits = rtp_llm::gumbelSample(logits, seeds, positions, temperatures, false, true);
    auto from_probs = rtp_llm::gumbelSample(probabilities, seeds, positions, target_temperatures, true, false);
    EXPECT_TRUE(torch::equal(from_logits, from_probs));
    EXPECT_TRUE(torch::equal(from_logits,
                             rtp_llm::gumbelSample(logits, seeds, positions, temperatures, false, true)));
    const auto sampled_argmax = from_logits[0].item<int64_t>();
    const auto expected_argmax = logits[0].argmax().item<int64_t>();
    EXPECT_EQ(sampled_argmax, expected_argmax);
}

TEST_F(SpeculativeSamplingKernelTest, GreedyTokenVerify_StopsAtFirstMismatchAndAddsBonus) {
    auto draft = torch::tensor(std::vector<int64_t>{1, 2, 3, 4, 5, 6, 7, 8, 9}, int64Cuda()).view({3, 3});
    auto target = torch::tensor(std::vector<int32_t>{1, 2, 3, 10, 40, 5, 6, 11, 7, 8, 90, 12}, intCuda())
                      .view({3, 4});

    auto [tokens, lengths] = rtp_llm::greedyTokenVerify(draft, target);

    auto expected_tokens = torch::tensor(std::vector<int32_t>{1, 2, 3, 10, 40, 0, 0, 0, 7, 8, 90, 0}, intCuda())
                               .view({3, 4});
    auto expected_lengths = torch::tensor(std::vector<int32_t>{4, 1, 3}, intCuda());
    EXPECT_TRUE(torch::equal(tokens, expected_tokens));
    EXPECT_TRUE(torch::equal(lengths, expected_lengths));
}

TEST_F(SpeculativeSamplingKernelTest, GreedyTokenVerify_SupportsInt32DraftAndInt64Target) {
    auto draft = torch::tensor(std::vector<int32_t>{3, 4}, intCuda()).view({1, 2});
    auto target = torch::tensor(std::vector<int64_t>{3, 9, 10}, int64Cuda()).view({1, 3});

    auto [tokens, lengths] = rtp_llm::greedyTokenVerify(draft, target);

    auto expected_tokens = torch::tensor(std::vector<int32_t>{3, 9, 0}, intCuda()).view({1, 3});
    auto expected_lengths = torch::tensor(std::vector<int32_t>{2}, intCuda());
    EXPECT_TRUE(torch::equal(tokens, expected_tokens));
    EXPECT_TRUE(torch::equal(lengths, expected_lengths));
}

// ─────────────────────────────────────────────────────────────────────────────
// invokeRejectionSampling tests
// ─────────────────────────────────────────────────────────────────────────────

TEST_F(SpeculativeSamplingKernelTest, RejectionSampling_AllAccept) {
    const int batch_size    = 2;
    const int num_spec      = 3;
    const int vocab_size    = 16;
    const int target_stride = 1;

    auto draft_probs  = torch::zeros({batch_size, num_spec, vocab_size}, floatCuda());
    auto target_probs = torch::zeros({batch_size, num_spec + 1, vocab_size}, floatCuda());

    // Both draft and target assign probability 1.0 to token 5
    draft_probs.index_put_({torch::indexing::Slice(), torch::indexing::Slice(), 5}, 1.0f);
    target_probs.index_put_({torch::indexing::Slice(), torch::indexing::Slice(), 5}, 1.0f);

    auto draft_token_ids = torch::full({batch_size, num_spec}, 5, intCuda());

    // target_token_ids: [batch, num_spec+1, target_stride], last column holds the argmax
    auto target_token_ids = torch::full({batch_size, num_spec + 1, target_stride}, 5, intCuda());

    auto uniform_samples     = torch::zeros({batch_size, num_spec + 1}, floatCuda());
    auto output_token_ids    = torch::full({batch_size, num_spec + 1}, -1, intCuda());
    auto output_accepted_num = torch::zeros({batch_size}, intCuda());
    auto do_sample           = torch::ones({batch_size}, boolCuda());

    auto status = rtp_llm::invokeRejectionSampling<float, int>(draft_probs.data_ptr<float>(),
                                                               draft_token_ids.data_ptr<int>(),
                                                               uniform_samples.data_ptr<float>(),
                                                               target_probs.data_ptr<float>(),
                                                               target_token_ids.data_ptr<int>(),
                                                               target_stride,
                                                               output_token_ids.data_ptr<int>(),
                                                               output_accepted_num.data_ptr<int>(),
                                                               do_sample.data_ptr<bool>(),
                                                               batch_size,
                                                               num_spec,
                                                               vocab_size,
                                                               true,
                                                               stream_);
    ASSERT_EQ(status, cudaSuccess);
    cudaStreamSynchronize(stream_);

    auto out_ids_h = output_token_ids.to(torch::kCPU);
    auto acc_num_h = output_accepted_num.to(torch::kCPU);

    for (int b = 0; b < batch_size; ++b) {
        // All speculative tokens accepted + bonus token = num_spec + 1
        EXPECT_EQ(acc_num_h[b].item<int>(), num_spec + 1);
        // First num_spec tokens should be draft token (5)
        for (int s = 0; s < num_spec; ++s) {
            EXPECT_EQ(out_ids_h[b][s].item<int>(), 5);
        }
        // Bonus token is target_token_ids[..., -1] = 5
        EXPECT_EQ(out_ids_h[b][num_spec].item<int>(), 5);
    }
}

TEST_F(SpeculativeSamplingKernelTest, RejectionSampling_ImmediateReject) {
    const int batch_size    = 1;
    const int num_spec      = 3;
    const int vocab_size    = 16;
    const int target_stride = 1;

    // Draft picks token 3, target picks token 7 — immediate mismatch
    auto draft_probs  = torch::zeros({batch_size, num_spec, vocab_size}, floatCuda());
    auto target_probs = torch::zeros({batch_size, num_spec + 1, vocab_size}, floatCuda());

    draft_probs.index_put_({torch::indexing::Slice(), torch::indexing::Slice(), 3}, 1.0f);
    target_probs.index_put_({torch::indexing::Slice(), torch::indexing::Slice(), 7}, 1.0f);

    auto draft_token_ids  = torch::full({batch_size, num_spec}, 3, intCuda());
    auto target_token_ids = torch::full({batch_size, num_spec + 1, target_stride}, 7, intCuda());

    // u = 0.5, p(draft_id=3) in target = 0 => u*p=0 which is NOT < q=0, so rejection
    // Actually: same_token is false, do_sample is false => reject
    auto uniform_samples     = torch::full({batch_size, num_spec + 1}, 0.5f, floatCuda());
    auto output_token_ids    = torch::full({batch_size, num_spec + 1}, -1, intCuda());
    auto output_accepted_num = torch::zeros({batch_size}, intCuda());
    auto do_sample           = torch::zeros({batch_size}, boolCuda());

    auto status = rtp_llm::invokeRejectionSampling<float, int>(draft_probs.data_ptr<float>(),
                                                               draft_token_ids.data_ptr<int>(),
                                                               uniform_samples.data_ptr<float>(),
                                                               target_probs.data_ptr<float>(),
                                                               target_token_ids.data_ptr<int>(),
                                                               target_stride,
                                                               output_token_ids.data_ptr<int>(),
                                                               output_accepted_num.data_ptr<int>(),
                                                               do_sample.data_ptr<bool>(),
                                                               batch_size,
                                                               num_spec,
                                                               vocab_size,
                                                               true,
                                                               stream_);
    ASSERT_EQ(status, cudaSuccess);
    cudaStreamSynchronize(stream_);

    auto acc_num_h = output_accepted_num.to(torch::kCPU);
    auto out_ids_h = output_token_ids.to(torch::kCPU);

    // Rejected at position 0, so accepted count = 0 + 1 = 1 (the resampled token)
    EXPECT_EQ(acc_num_h[0].item<int>(), 1);
    // The resampled token at pos 0 should come from relu(q-p); target_probs is all on token 7,
    // so the resampled token should be 7
    EXPECT_EQ(out_ids_h[0][0].item<int>(), 7);
    // Remaining positions padded with -1
    EXPECT_EQ(out_ids_h[0][1].item<int>(), -1);
    EXPECT_EQ(out_ids_h[0][2].item<int>(), -1);
    EXPECT_EQ(out_ids_h[0][3].item<int>(), -1);
}

TEST_F(SpeculativeSamplingKernelTest, RejectionSampling_PartialAccept) {
    const int batch_size    = 1;
    const int num_spec      = 3;
    const int vocab_size    = 16;
    const int target_stride = 1;

    auto draft_probs  = torch::zeros({batch_size, num_spec, vocab_size}, floatCuda());
    auto target_probs = torch::zeros({batch_size, num_spec + 1, vocab_size}, floatCuda());

    // Position 0: draft=5, target argmax=5 → same_token → accept
    // Position 1: draft=5, target argmax=5 → same_token → accept
    // Position 2: draft=3, target argmax=7 → mismatch, do_sample=false → reject
    draft_probs.index_put_({torch::indexing::Slice(), torch::indexing::Slice(), 5}, 1.0f);
    draft_probs.index_put_({torch::indexing::Slice(), 2, 5}, 0.0f);
    draft_probs.index_put_({torch::indexing::Slice(), 2, 3}, 1.0f);

    target_probs.index_put_({torch::indexing::Slice(), torch::indexing::Slice(), 7}, 1.0f);

    auto draft_token_ids = torch::full({batch_size, num_spec}, 5, intCuda());
    draft_token_ids.index_put_({torch::indexing::Slice(), 2}, 3);

    auto target_token_ids = torch::full({batch_size, num_spec + 1, target_stride}, 5, intCuda());
    // Position 0,1 target matches draft (token 5)
    // Position 2 target is different (token 7)
    target_token_ids.index_put_({torch::indexing::Slice(), 2, 0}, 7);
    target_token_ids.index_put_({torch::indexing::Slice(), 3, 0}, 7);

    auto uniform_samples     = torch::full({batch_size, num_spec + 1}, 0.5f, floatCuda());
    auto output_token_ids    = torch::full({batch_size, num_spec + 1}, -1, intCuda());
    auto output_accepted_num = torch::zeros({batch_size}, intCuda());
    auto do_sample           = torch::zeros({batch_size}, boolCuda());

    auto status = rtp_llm::invokeRejectionSampling<float, int>(draft_probs.data_ptr<float>(),
                                                               draft_token_ids.data_ptr<int>(),
                                                               uniform_samples.data_ptr<float>(),
                                                               target_probs.data_ptr<float>(),
                                                               target_token_ids.data_ptr<int>(),
                                                               target_stride,
                                                               output_token_ids.data_ptr<int>(),
                                                               output_accepted_num.data_ptr<int>(),
                                                               do_sample.data_ptr<bool>(),
                                                               batch_size,
                                                               num_spec,
                                                               vocab_size,
                                                               true,
                                                               stream_);
    ASSERT_EQ(status, cudaSuccess);
    cudaStreamSynchronize(stream_);

    auto acc_num_h = output_accepted_num.to(torch::kCPU);
    auto out_ids_h = output_token_ids.to(torch::kCPU);

    // Accepted positions 0, 1, rejected at 2 → count = 2 + 1 = 3
    EXPECT_EQ(acc_num_h[0].item<int>(), 3);
    EXPECT_EQ(out_ids_h[0][0].item<int>(), 5);
    EXPECT_EQ(out_ids_h[0][1].item<int>(), 5);
    // Resampled from relu(q-p) at position 2; target has all prob on token 7
    EXPECT_EQ(out_ids_h[0][2].item<int>(), 7);
    EXPECT_EQ(out_ids_h[0][3].item<int>(), -1);
}

TEST_F(SpeculativeSamplingKernelTest, RejectionSampling_BatchSizeZero) {
    auto status = rtp_llm::invokeRejectionSampling<float, int>(
        nullptr, nullptr, nullptr, nullptr, nullptr, 1, nullptr, nullptr, nullptr, 0, 3, 16, false, stream_);
    ASSERT_EQ(status, cudaSuccess);
}

TEST_F(SpeculativeSamplingKernelTest, RejectionSampling_ProbabilisticSameTokenStillUsesRatio) {
    const int batch_size    = 1;
    const int num_spec      = 1;
    const int vocab_size    = 16;
    const int target_stride = 1;

    auto draft_probs  = torch::zeros({batch_size, num_spec, vocab_size}, floatCuda());
    auto target_probs = torch::zeros({batch_size, num_spec + 1, vocab_size}, floatCuda());
    draft_probs.index_put_({0, 0, 3}, 0.9f);
    draft_probs.index_put_({0, 0, 7}, 0.1f);
    target_probs.index_put_({0, 0, 3}, 0.1f);
    target_probs.index_put_({0, 0, 7}, 0.9f);
    target_probs.index_put_({0, 1, 7}, 1.0f);

    auto draft_token_ids  = torch::full({batch_size, num_spec}, 3, intCuda());
    // Deliberately report the same independently sampled target token.  The
    // ratio 0.5 * 0.9 < 0.1 is false, so this row must still reject.
    auto target_token_ids = torch::full({batch_size, num_spec + 1, target_stride}, 3, intCuda());
    auto uniform_samples  = torch::tensor({{0.5f, 0.0f}}, floatCuda());
    auto output_token_ids = torch::full({batch_size, num_spec + 1}, -1, intCuda());
    auto output_accepted_token_num = torch::zeros({batch_size}, intCuda());
    auto do_sample = torch::ones({batch_size}, boolCuda());

    auto status = rtp_llm::invokeRejectionSampling<float, int>(draft_probs.data_ptr<float>(),
                                                               draft_token_ids.data_ptr<int>(),
                                                               uniform_samples.data_ptr<float>(),
                                                               target_probs.data_ptr<float>(),
                                                               target_token_ids.data_ptr<int>(),
                                                               target_stride,
                                                               output_token_ids.data_ptr<int>(),
                                                               output_accepted_token_num.data_ptr<int>(),
                                                               do_sample.data_ptr<bool>(),
                                                               batch_size,
                                                               num_spec,
                                                               vocab_size,
                                                               true,
                                                               stream_);
    ASSERT_EQ(status, cudaSuccess);
    cudaStreamSynchronize(stream_);
    EXPECT_EQ(output_accepted_token_num.cpu()[0].item<int>(), 1);
    EXPECT_EQ(output_token_ids.cpu()[0][0].item<int>(), 7);
}

TEST_F(SpeculativeSamplingKernelTest, RejectionSampling_ImplicitOneHotDraftDistribution) {
    const int batch_size    = 1;
    const int num_spec      = 1;
    const int vocab_size    = 16;
    const int target_stride = 1;

    auto target_probs = torch::zeros({batch_size, num_spec + 1, vocab_size}, floatCuda());
    target_probs.index_put_({0, 0, 3}, 0.1f);
    target_probs.index_put_({0, 0, 7}, 0.9f);
    target_probs.index_put_({0, 1, 7}, 1.0f);
    auto draft_token_ids  = torch::full({batch_size, num_spec}, 3, intCuda());
    auto target_token_ids = torch::full({batch_size, num_spec + 1, target_stride}, 3, intCuda());
    auto uniform_samples  = torch::tensor({{0.5f, 0.0f}}, floatCuda());
    auto output_token_ids = torch::full({batch_size, num_spec + 1}, -1, intCuda());
    auto output_accepted_token_num = torch::zeros({batch_size}, intCuda());
    auto do_sample = torch::ones({batch_size}, boolCuda());

    // No draft_probs allocation: q is the one-hot distribution at proposal 3.
    auto status = rtp_llm::invokeRejectionSampling<float, int>(nullptr,
                                                               draft_token_ids.data_ptr<int>(),
                                                               uniform_samples.data_ptr<float>(),
                                                               target_probs.data_ptr<float>(),
                                                               target_token_ids.data_ptr<int>(),
                                                               target_stride,
                                                               output_token_ids.data_ptr<int>(),
                                                               output_accepted_token_num.data_ptr<int>(),
                                                               do_sample.data_ptr<bool>(),
                                                               batch_size,
                                                               num_spec,
                                                               vocab_size,
                                                               false,
                                                               stream_);
    ASSERT_EQ(status, cudaSuccess);
    cudaStreamSynchronize(stream_);
    EXPECT_EQ(output_accepted_token_num.cpu()[0].item<int>(), 1);
    // Residual is p with the proposal coordinate removed, hence token 7.
    EXPECT_EQ(output_token_ids.cpu()[0][0].item<int>(), 7);
}

// ─────────────────────────────────────────────────────────────────────────────
// invokeMappingDraft2Target tests
// ─────────────────────────────────────────────────────────────────────────────

TEST_F(SpeculativeSamplingKernelTest, MappingDraft2Target_Basic) {
    const int batch_size   = 2;
    const int token_stride = 4;
    const int token_offset = 0;
    const int map_size     = 8;

    // d2t_map: draft token i → target token (i * 10)
    std::vector<int64_t> map_host(map_size);
    for (int i = 0; i < map_size; ++i)
        map_host[i] = i * 10;
    auto d2t_map = torch::from_blob(map_host.data(), {map_size}, torch::kInt64).to(torch::kCUDA);

    // tokens: [[0,1,2,3], [4,5,6,7]]
    auto tokens = torch::tensor({{0, 1, 2, 3}, {4, 5, 6, 7}}, intCuda());

    rtp_llm::invokeMappingDraft2Target<int32_t>(tokens.data_ptr<int32_t>(),
                                                batch_size,
                                                token_offset,
                                                token_stride,
                                                d2t_map.data_ptr<int64_t>(),
                                                map_size,
                                                stream_);
    cudaStreamSynchronize(stream_);

    auto tokens_h = tokens.to(torch::kCPU);
    EXPECT_EQ(tokens_h[0][0].item<int>(), 0);
    EXPECT_EQ(tokens_h[0][1].item<int>(), 10);
    EXPECT_EQ(tokens_h[0][2].item<int>(), 20);
    EXPECT_EQ(tokens_h[0][3].item<int>(), 30);
    EXPECT_EQ(tokens_h[1][0].item<int>(), 40);
    EXPECT_EQ(tokens_h[1][1].item<int>(), 50);
    EXPECT_EQ(tokens_h[1][2].item<int>(), 60);
    EXPECT_EQ(tokens_h[1][3].item<int>(), 70);
}

TEST_F(SpeculativeSamplingKernelTest, MappingDraft2Target_WithOffset) {
    const int batch_size   = 1;
    const int token_stride = 4;
    const int token_offset = 2;
    const int map_size     = 8;

    std::vector<int64_t> map_host(map_size);
    for (int i = 0; i < map_size; ++i)
        map_host[i] = i + 100;
    auto d2t_map = torch::from_blob(map_host.data(), {map_size}, torch::kInt64).to(torch::kCUDA);

    // tokens: [0, 1, 2, 3]; only positions 2,3 should be mapped
    auto tokens = torch::tensor({0, 1, 2, 3}, intCuda());

    rtp_llm::invokeMappingDraft2Target<int32_t>(tokens.data_ptr<int32_t>(),
                                                batch_size,
                                                token_offset,
                                                token_stride,
                                                d2t_map.data_ptr<int64_t>(),
                                                map_size,
                                                stream_);
    cudaStreamSynchronize(stream_);

    auto tokens_h = tokens.to(torch::kCPU);
    EXPECT_EQ(tokens_h[0].item<int>(), 0);    // unchanged (before offset)
    EXPECT_EQ(tokens_h[1].item<int>(), 1);    // unchanged (before offset)
    EXPECT_EQ(tokens_h[2].item<int>(), 102);  // mapped: d2t_map[2]
    EXPECT_EQ(tokens_h[3].item<int>(), 103);  // mapped: d2t_map[3]
}

TEST_F(SpeculativeSamplingKernelTest, MappingDraft2Target_NegativeTokensUnchanged) {
    const int batch_size   = 1;
    const int token_stride = 4;
    const int token_offset = 0;
    const int map_size     = 8;

    std::vector<int64_t> map_host(map_size);
    for (int i = 0; i < map_size; ++i)
        map_host[i] = i + 100;
    auto d2t_map = torch::from_blob(map_host.data(), {map_size}, torch::kInt64).to(torch::kCUDA);

    // tokens contain -1 (padding) — should be left unchanged
    auto tokens = torch::tensor({2, -1, 5, -1}, intCuda());

    rtp_llm::invokeMappingDraft2Target<int32_t>(tokens.data_ptr<int32_t>(),
                                                batch_size,
                                                token_offset,
                                                token_stride,
                                                d2t_map.data_ptr<int64_t>(),
                                                map_size,
                                                stream_);
    cudaStreamSynchronize(stream_);

    auto tokens_h = tokens.to(torch::kCPU);
    EXPECT_EQ(tokens_h[0].item<int>(), 102);  // mapped
    EXPECT_EQ(tokens_h[1].item<int>(), -1);   // negative → unchanged
    EXPECT_EQ(tokens_h[2].item<int>(), 105);  // mapped
    EXPECT_EQ(tokens_h[3].item<int>(), -1);   // negative → unchanged
}

TEST_F(SpeculativeSamplingKernelTest, MappingDraft2Target_OutOfRangeUnchanged) {
    const int batch_size   = 1;
    const int token_stride = 3;
    const int token_offset = 0;
    const int map_size     = 4;

    std::vector<int64_t> map_host = {100, 101, 102, 103};
    auto                 d2t_map  = torch::from_blob(map_host.data(), {map_size}, torch::kInt64).to(torch::kCUDA);

    // Token 10 is out of range for map_size=4 — should be left unchanged
    auto tokens = torch::tensor({1, 10, 3}, intCuda());

    rtp_llm::invokeMappingDraft2Target<int32_t>(tokens.data_ptr<int32_t>(),
                                                batch_size,
                                                token_offset,
                                                token_stride,
                                                d2t_map.data_ptr<int64_t>(),
                                                map_size,
                                                stream_);
    cudaStreamSynchronize(stream_);

    auto tokens_h = tokens.to(torch::kCPU);
    EXPECT_EQ(tokens_h[0].item<int>(), 101);  // mapped
    EXPECT_EQ(tokens_h[1].item<int>(), 10);   // out of range → unchanged
    EXPECT_EQ(tokens_h[2].item<int>(), 103);  // mapped
}
