# This is a basic workflow to help you get started with Actions

name: CI Request Trigger

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # work on CI script dir
    defaults:
      run:
        working-directory: .github/scripts
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs trigger CI
      - name: Make the script files executable
        run: chmod +x trigger-CI.sh get-CI-result.sh
      - name: trigger a CI
        run: |
          ./trigger-CI.sh "${{ github.sha }}" "${{ secrets.CI_SECRET }}"

      # Runs get CI result
      - name: Get CI result
        run: |
          ./get-CI-result.sh "${{ github.sha }}" "${{ secrets.CI_SECRET }}"