package org.flexlb.cache.hash;

import com.fasterxml.jackson.dataformat.cbor.CBORGenerator;
import org.flexlb.config.ConfigService;
import org.flexlb.service.config.ConfigSource;
import org.junit.jupiter.api.Test;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.HexFormat;
import java.util.List;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import java.util.function.Consumer;
import java.util.stream.IntStream;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertSame;
import static org.junit.jupiter.api.Assertions.assertThrows;

class VllmBlockHashStrategyTest {

    private static final int THREAD_COUNT = 16;
    private static final int REQUEST_COUNT = 320;
    private static final int INPUT_VARIANT_COUNT = 4;
    private static final int TOKEN_COUNT = 20_480;
    private static final int BLOCK_SIZE = 64;
    private static final HexFormat HEX = HexFormat.of();
    // Generated by vLLM sha256_cbor with PYTHONHASHSEED=0.
    private static final String NONE_HASH =
            "4e1195df020de59e0d65a33a4279f1183e7ae4e5d980e309f8b55adff2e61c3e";

    private final VllmBlockHashStrategy strategy = new VllmBlockHashStrategy();

    @Test
    void encodesHashSeedExactlyLikeVllmCanonicalCbor() throws Exception {
        byte[] encodedSeed = encode(generator -> VllmBlockHashStrategy.writeHashSeed(generator, "0"));

        assertEquals("6130", HEX.formatHex(encodedSeed));
        assertEquals(NONE_HASH, sha256Hex(encodedSeed));
    }

    @Test
    void encodesCanonicalIntegerBoundariesExactlyLikeVllm() throws Exception {
        int[] inputIds = {
                0, 23, 24, 255, 256, 65535, 65536, Integer.MAX_VALUE};
        byte[] encodedBlock = encode(generator -> VllmBlockHashStrategy.writeBlock(
                generator, HEX.parseHex(NONE_HASH), inputIds, 0, inputIds.length));

        assertEquals(
                "8358204e1195df020de59e0d65a33a4279f1183e7ae4e5d980e309f8b55adff2e61c3e"
                        + "880017181818ff19010019ffff1a000100001a7ffffffff6",
                HEX.formatHex(encodedBlock));
        assertEquals(
                "946e7cc9f82671eb436b48a434e33c2b8bc9bd9eb03ef4b721002a2fa2fef37c",
                sha256Hex(encodedBlock));
        assertEquals(
                List.of(2377946987338068860L),
                strategy.calculate(inputIds, inputIds.length, 0));
    }

    @Test
    void matchesVllmSingleBlockFullHashAndCacheKey() throws Exception {
        int[] inputIds = {1, 2, 3, 4};
        byte[] blockHash = hashBlock(HEX.parseHex(NONE_HASH), inputIds, 0, 4);

        assertEquals(
                "c9d58ba695280d69b243e1e0df813136ca9196b286fb1a021e0b2e028ef071cb",
                HEX.formatHex(blockHash));
        assertEquals(
                List.of(2164874634404590027L),
                strategy.calculate(inputIds, 4, 0));
    }

    @Test
    void matchesVllmChainedBlockFullHashesAndSignedCacheKeys() throws Exception {
        int[] inputIds = IntStream.range(0, 128).toArray();
        byte[] firstBlockHash = hashBlock(HEX.parseHex(NONE_HASH), inputIds, 0, 64);
        byte[] secondBlockHash = hashBlock(firstBlockHash, inputIds, 64, 64);

        assertEquals(
                "ddfc07d6c65195c803c8619358c7b0ae3aabee104d3bc6e59787c2001f45d77a",
                HEX.formatHex(firstBlockHash));
        assertEquals(
                "c61732f6553f8367340fd94d0d76c692b13f865bec1cf6b092e8bedefdf74b3e",
                HEX.formatHex(secondBlockHash));
        assertEquals(
                List.of(-7527834946346035334L, -7860823284622341314L),
                strategy.calculate(inputIds, 64, 0));
    }

    @Test
    void matchesVllmEagleHashesWithOneLookaheadToken() {
        int[] inputIds = IntStream.rangeClosed(1, 9).toArray();

        assertEquals(
                List.of(2771287707320467766L, -4525836348354197114L),
                strategy.calculate(inputIds, 4, 1));
    }

    @Test
    void dropsFinalPartialBlock() {
        int[] inputIds = IntStream.range(0, 130).toArray();

        assertEquals(
                List.of(-7527834946346035334L, -7860823284622341314L),
                strategy.calculate(inputIds, 64, 0));
    }

    @Test
    void returnsEmptyListWhenThereIsNoCompleteBlock() {
        assertEquals(List.of(), strategy.calculate(new int[]{1, 2}, 4, 0));
    }

    @Test
    void rejectsInvalidInput() {
        assertThrows(
                IllegalArgumentException.class,
                () -> strategy.calculate(null, 1, 0));
        assertThrows(
                IllegalArgumentException.class,
                () -> strategy.calculate(new int[]{1}, 0, 0));
        assertThrows(
                IllegalArgumentException.class,
                () -> strategy.calculate(new int[]{1}, 1, -1));
    }

    @Test
    void keepsAllCalculatedBlocksInTheCacheablePrefix() {
        List<Long> hashes = List.of(11L, 22L);

        assertSame(hashes, strategy.cacheablePrefix(hashes, 9, 4, 1));
    }

    @Test
    void appliesInitialSeedThenUpdatesAndFallsBackForMissingConfig() {
        FakeConfigSource source = new FakeConfigSource(
                "Nacos", 200, "{\"blockHashConfig\":{\"hashSeed\":\"1\"}}");
        ConfigService.register(source);
        ConfigService configService = new ConfigService();
        VllmBlockHashStrategy dynamicStrategy = new VllmBlockHashStrategy(configService);

        try {
            assertEquals(
                    List.of(2107465152829418342L),
                    dynamicStrategy.calculate(new int[]{1, 2, 3, 4}, 4, 0));

            source.emit("{\"blockHashConfig\":{\"hashSeed\":\"0\"}}");

            assertEquals(
                    List.of(2164874634404590027L),
                    dynamicStrategy.calculate(new int[]{1, 2, 3, 4}, 4, 0));

            source.emit("{\"blockHashConfig\":{\"hashSeed\":null}}");

            assertEquals(
                    List.of(2164874634404590027L),
                    dynamicStrategy.calculate(new int[]{1, 2, 3, 4}, 4, 0));

            source.emit("{\"blockHashConfig\":null}");

            assertEquals(
                    List.of(2164874634404590027L),
                    dynamicStrategy.calculate(new int[]{1, 2, 3, 4}, 4, 0));
        } finally {
            configService.close();
        }
    }

    @Test
    void producesStableResultsUnderConcurrentLoad() throws Exception {
        List<int[]> inputs = new ArrayList<>(INPUT_VARIANT_COUNT);
        List<List<Long>> expectedResults = new ArrayList<>(INPUT_VARIANT_COUNT);
        for (int variant = 0; variant < INPUT_VARIANT_COUNT; variant++) {
            int firstTokenId = variant * 100_000;
            int[] inputIds = IntStream.range(firstTokenId, firstTokenId + TOKEN_COUNT).toArray();
            inputs.add(inputIds);
            expectedResults.add(strategy.calculate(inputIds, BLOCK_SIZE, 0));
        }

        ExecutorService executor = Executors.newFixedThreadPool(THREAD_COUNT);
        CountDownLatch startGate = new CountDownLatch(1);
        List<Future<List<Long>>> futures = new ArrayList<>(REQUEST_COUNT);
        try {
            for (int requestIndex = 0; requestIndex < REQUEST_COUNT; requestIndex++) {
                int inputIndex = requestIndex % INPUT_VARIANT_COUNT;
                futures.add(executor.submit(() -> {
                    startGate.await();
                    return strategy.calculate(inputs.get(inputIndex), BLOCK_SIZE, 0);
                }));
            }

            startGate.countDown();
            for (int requestIndex = 0; requestIndex < REQUEST_COUNT; requestIndex++) {
                int inputIndex = requestIndex % INPUT_VARIANT_COUNT;
                assertEquals(
                        expectedResults.get(inputIndex),
                        futures.get(requestIndex).get(30, TimeUnit.SECONDS));
            }
        } finally {
            startGate.countDown();
            executor.shutdownNow();
            executor.awaitTermination(5, TimeUnit.SECONDS);
        }
    }

    private static byte[] hashBlock(
            byte[] parentHash,
            int[] inputIds,
            int tokenOffset,
            int blockSize) throws Exception {
        return MessageDigest.getInstance("SHA-256").digest(encode(generator ->
                VllmBlockHashStrategy.writeBlock(
                        generator, parentHash, inputIds, tokenOffset, blockSize)));
    }

    private static String sha256Hex(byte[] value) throws NoSuchAlgorithmException {
        return HEX.formatHex(MessageDigest.getInstance("SHA-256").digest(value));
    }

    private static byte[] encode(CborWriter writer) throws IOException {
        ByteArrayOutputStream output = new ByteArrayOutputStream();
        try (CBORGenerator generator = VllmBlockHashStrategy.newCborGenerator(output)) {
            writer.write(generator);
        }
        return output.toByteArray();
    }

    @FunctionalInterface
    private interface CborWriter {
        void write(CBORGenerator generator) throws IOException;
    }

    private static final class FakeConfigSource implements ConfigSource {
        private final String name;
        private final int priority;
        private final String initialContent;
        private Consumer<String> listener;

        private FakeConfigSource(String name, int priority, String initialContent) {
            this.name = name;
            this.priority = priority;
            this.initialContent = initialContent;
        }

        @Override
        public String name() {
            return name;
        }

        @Override
        public int priority() {
            return priority;
        }

        @Override
        public void setUpdateListener(Consumer<String> listener) {
            this.listener = listener;
        }

        @Override
        public String load() {
            return initialContent;
        }

        private void emit(String content) {
            listener.accept(content);
        }
    }
}
