"""Single source of truth for the SM matrix.

Key = bazelrc baseline config name; value = the GPU architecture list for that config.
CUDA entries use the x.y form of TF_CUDA_COMPUTE_CAPABILITIES; release configs must stay in
x.y (i.e. compute_XX) form to retain PTX; the sm_ prefix is forbidden — only compute_XX emits
--cuda-include-ptx, and a wheel built as sm_XX simply cannot start on new cards outside the matrix.
ROCm entries use the gfxNNN form of GPU_ARCHS.

Version configs (cuda12_2/cuda12_6/cuda12_9) are not here — they only change TF_CUDA_VERSION;
SM is inherited from the cuda12 baseline.

The derived bazel/sm.bazelrc is generated by deps/gen_sm_bazelrc.py; hand-editing is forbidden;
`scripts/rtpcli deps check --all` pins the derivation consistency.
"""

CUDA_SM_MATRIX = {
    "cuda12": "7.0,7.5,8.0,8.6,8.9,9.0",
    "cuda12_9_arm": "10.0",
    "cuda13": "8.0,8.6,8.9,9.0,10.0",
    "cuda13_arm": "10.0",
}

ROCM_ARCH_MATRIX = {
    "rocm": "gfx942",
    "rocm_gfx950": "gfx950",
}

# Override knob: --config=cuda12 --config=sm9x, the latter overrides the former
SM_KNOBS = {
    "sm7x": "7.0,7.5",
    "sm8x": "8.0,8.6,8.9",
    "sm9x": "9.0",
    "sm10x": "10.0",
    "sm12x": "12.0",
}
