package(default_visibility = ["//rtp_llm:__subpackages__"])

py_library(
    name = "distribute",
    srcs = glob(["*.py"]),
    deps = [
        "//rtp_llm/models_py/distributed:collective_torch",
    ],
)
