spring:
  application:
    name: flexlb-api
  profiles:
    active: default
  main:
    web-application-type: reactive
  codec:
    max-in-memory-size: ${MAX_IN_MEMORY_SIZE:10MB}
logging:
  group:
    flexlb: org.flexlb,flexlbLogger,syncLogger,syncConsistencyLogger
  level:
    root: info
    io.grpc: info
    com.google.protobuf: info
    org.flexlb.utils.LoggingUtils: trace
server:
  port: 7001

management:
  server:
    port: 7002
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"
  metrics:
    tags:
      application: flexlb-api

flexlb:
  monitor:
    enabled: true
    per-engine-tags: true
    # Use --flexlb.monitor.metric-whitelist to select exposed metric prefixes.
