py_test(
    name = "xgrammar_hot_path_static_check",
    srcs = ["xgrammar_hot_path_static_check.py"],
    data = [
        "//rtp_llm/cpp/models:xgrammar_hot_path_sources",
    ],
    visibility = ["//visibility:public"],
)
