py_test(
    name = "dsv4_kv_cache_test",
    srcs = ["dsv4_kv_cache_test.py"],
    deps = ["//rtp_llm:testlib"],
    exec_properties = {"gpu": "H20"},
)

py_test(
    name = "deepseek_v4_dspark_commit_only_test",
    srcs = ["deepseek_v4_dspark_commit_only_test.py"],
    deps = ["//rtp_llm:testlib"],
    exec_properties = {"gpu": "H20"},
)
