"""CUDA-specific attention output gate module (Qwen3.5).

nn.Module wrapper around the Triton kernel in
rtp_llm.models_py.triton_kernels.common.attn_output_gate.

Fuses `attn_output * sigmoid(gate)` into a single kernel, replacing
the two-kernel sequence (sigmoid + mul) generated by the eager path.
"""

import torch
import torch.nn as nn

from rtp_llm.models_py.triton_kernels.common.attn_output_gate import (
    sigmoid_mul_inplace_triton,
)


class SigmoidMulInplace(nn.Module):
    """Fused sigmoid-mul module for Qwen3.5 attention output gate (CUDA/Triton)."""

    def forward(
        self,
        attn_output: torch.Tensor,
        gate: torch.Tensor,
    ) -> torch.Tensor:
        return sigmoid_mul_inplace_triton(attn_output, gate)
