"""RTP-LLM OTel trace telemetry (trace-only signal, off unless enabled by env)."""

from rtp_llm.telemetry.tracing import (
    CURRENT_TRACE_STATE,
    OTEL_AVAILABLE,
    ClientSpanHandle,
    RequestTraceState,
    TelemetryState,
    extract_context_from_headers,
    get_tracer,
    init_telemetry,
    init_telemetry_for_test,
    inject_context_to_metadata,
    is_telemetry_active,
    record_response_attributes,
    resolve_endpoint,
    resolve_region_env,
    shutdown_telemetry,
    start_client_span,
    start_internal_span,
    start_server_span,
    telemetry_state,
)

__all__ = [
    "CURRENT_TRACE_STATE",
    "OTEL_AVAILABLE",
    "ClientSpanHandle",
    "RequestTraceState",
    "TelemetryState",
    "extract_context_from_headers",
    "get_tracer",
    "init_telemetry",
    "init_telemetry_for_test",
    "inject_context_to_metadata",
    "is_telemetry_active",
    "record_response_attributes",
    "resolve_endpoint",
    "resolve_region_env",
    "shutdown_telemetry",
    "start_client_span",
    "start_internal_span",
    "start_server_span",
    "telemetry_state",
]
