py_test(
    name = "foundation_test",
    srcs = ["foundation_test.py"],
    deps = [
        "//rtp_llm/models_py:new_weight_loader",
        "//rtp_llm:safetensors",
        "//rtp_llm:torch",
    ],
)
