package(default_visibility = ["//maga_transformer:__subpackages__", "//internal_source:__subpackages__"])

py_library(
    name = "test_util",
    srcs = glob(["*.py"]),
    deps = [
        "//maga_transformer:testlib"
    ]
)