package(default_visibility = ["//visibility:public"])

py_library(
    name = "device_resource",
    deps = [],
    srcs = ["device_resource.py"],
    visibility = ["//visibility:public"],
)
py_library(
    name = "port_util",
    deps = [],
    srcs = ["port_util.py"],
    visibility = ["//visibility:public"],
)