cc_test(
    name = "deferred_read_queue_test",
    srcs = ["DeferredReadQueueTest.cc"],
    deps = [
        "//rtp_llm/cpp/rdma_transport:deferred_read_queue",
        "@com_google_googletest//:gtest_main",
    ],
)
