py_test(
    name = "legacy_fp8_indexer_score_test",
    srcs = ["legacy_fp8_indexer_score_test.py"],
    deps = ["//rtp_llm:testlib"],
    exec_properties = {"gpu": "SM100_ARM_CU13", "gpu_count": "1"},
    tags = ["SM100_ARM_CU13"],
)
