py_library(
    name = "metrics",
    srcs = glob([
        "*.py"
    ]),
    visibility = ["//visibility:public"],
    deps = ["//rtp_llm/aios/kmonitor:kmonitor_py",
            "//rtp_llm/distribute:distribute"],
)
