load("//:def.bzl", "copts", "cuda_copts")

py_test(
    name = "test_embedding_profile_config",
    srcs = [
        "test_embedding_profile_config.py",
    ],
    deps = [
        "//rtp_llm:rtp_llm_lib",
    ],
)
