py_test(
    name = "test_embedding_profile_config",
    srcs = [
        "test_embedding_profile_config.py",
    ],
    deps = [
        "//rtp_llm:testlib",
    ],
    exec_properties = {'gpu':'H20'},
)
