py_test(
    name = "test_dspark_proposer",
    srcs = ["test_dspark_proposer.py"],
    main = "test_dspark_proposer.py",
    deps = ["//rtp_llm/models_py/standalone:py_standalone_testlib"],
)

py_test(
    name = "test_dspark_reference",
    srcs = ["test_dspark_reference.py"],
    main = "test_dspark_reference.py",
    deps = ["//rtp_llm/models_py/standalone:py_standalone_testlib"],
)

py_test(
    name = "test_dspark_single_simulator",
    srcs = ["test_dspark_single_simulator.py"],
    main = "test_dspark_single_simulator.py",
    deps = ["//rtp_llm/models_py/standalone:py_standalone_testlib"],
)

py_test(
    name = "test_single_dspark_closed_loop",
    srcs = ["test_single_dspark_closed_loop.py"],
    main = "test_single_dspark_closed_loop.py",
    deps = ["//rtp_llm/models_py/standalone:py_standalone_testlib"],
)

py_test(
    name = "test_dspark_runtime_config",
    srcs = ["test_dspark_runtime_config.py"],
    main = "test_dspark_runtime_config.py",
    deps = ["//rtp_llm:testlib"],
)
