py_test(
    name = "test_dspark_proposer",
    srcs = ["test_dspark_proposer.py"],
    deps = [
        "//rtp_llm/models_py/standalone:py_standalone_testlib",
    ],
)

py_test(
    name = "test_qwen3_dspark",
    srcs = ["test_qwen3_dspark.py"],
    deps = [
        "//rtp_llm:async_model",
        "//rtp_llm:models",
        "//rtp_llm/models_py/standalone:py_standalone_testlib",
    ],
)
