package(default_visibility = ["//:__subpackages__"])

py_library(
    name = "tipc",
    srcs = [
        "__init__.py",
        "core.py",
        "html.py"
    ],
    deps = [
        "//rtp_llm/tools/tipc/cpp:tipc_lib",
    ]
)