cc_binary(
    name = "rr_load_balancer_main",
    srcs = [
        "RRLoadBalancerMain.cpp",
    ],
    deps = [
        "//maga_transformer/cpp/disaggregate/load_balancer:load_balancer",
    ],
    linkstatic = True,
)