"""V4.1 cache tags, shared with declarative cache specifications."""

SWA_KV = "swa_kv"
DECODER_SWA_KV = "decoder_swa_kv"
CSA_KV = "global_kv_2"
HCA_KV = "global_kv_1"
INDEXER_KV = "indexer_kv"
INDEXER_STATE = "indexer_state"
CSA_STATE = "csa_state"
HCA_STATE = "hca_state"
