py_test(
    name = "test_stream_usage_split",
    srcs = ["test_stream_usage_split.py"],
    deps = [
        "//rtp_llm:testlib",
    ],
)

py_test(
    name = "test_stream_content_preservation",
    srcs = ["test_stream_content_preservation.py"],
    deps = [
        "//rtp_llm:testlib",
    ],
)
