load("//rtp_llm/test/smoke:defs.bzl", "smoke_test")

def remote_cache_suites():

    # PPU Remote Cache (with KVCM server)
    native.test_suite(
        name = "smoke_cuda_remote_cache",
        tests = [
            smoke_test(
                name = "remote_cache_basic",
                data = ["@remote_kv_cache_manager_server//:bin/kv_cache_manager_bin"],
                gpu_type = ["L20"],
                kvcm_envs = ["SEQ_SIZE_PER_BLOCK=8", "KVCM_LOG_LEVEL=DEBUG"],
                smoke_args = "--warm_up 0 --reuse_cache 1 --act_type FP16 --seq_size_per_block 8 --write_cache_sync 1 --enable_remote_cache true --enable_device_cache 0 --deterministic_attn 1",
                task_info = "data/model/qwen25/q_r_l20_remote_cache.json",
            ),
            smoke_test(
                name = "remote_cache_basic_async",
                data = ["@remote_kv_cache_manager_server//:bin/kv_cache_manager_bin"],
                gpu_type = ["L20"],
                kvcm_envs = ["SEQ_SIZE_PER_BLOCK=8", "KVCM_LOG_LEVEL=DEBUG"],
                sleep_time_qr = 10,
                smoke_args = "--warm_up 0 --reuse_cache 1 --act_type FP16 --seq_size_per_block 8 --enable_remote_cache true --enable_device_cache 0 --deterministic_attn 1",
                task_info = "data/model/qwen25/q_r_l20_remote_cache.json",
            ),
            smoke_test(
                name = "remote_cache_kill",
                data = ["@remote_kv_cache_manager_server//:bin/kv_cache_manager_bin"],
                gpu_type = ["L20"],
                kill_remote = True,
                kvcm_envs = ["SEQ_SIZE_PER_BLOCK=8", "KVCM_LOG_LEVEL=DEBUG"],
                sleep_time_qr = 10,
                smoke_args = "--warm_up 0 --reuse_cache 1 --act_type FP16 --seq_size_per_block 8 --enable_remote_cache true --enable_device_cache 0",
                task_info = "data/model/qwen25/q_r_l20_remote_cache_kill_remote.json",
            ),
            smoke_test(
                name = "remote_cache_tp2",
                data = ["@remote_kv_cache_manager_server//:bin/kv_cache_manager_bin"],
                gpu_type = ["L20"],
                kvcm_envs = ["SEQ_SIZE_PER_BLOCK=8", "KVCM_LOG_LEVEL=DEBUG"],
                sleep_time_qr = 20,
                smoke_args = "--warm_up 0 --reuse_cache 1 --act_type FP16 --seq_size_per_block 8 --tp_size 2 --enable_remote_cache true --enable_device_cache 0 --reco_put_timeout_ms 12000 --reco_get_timeout_ms 12000 --reco_get_broadcast_timeout 15000 --reco_put_broadcast_timeout 15000",
                task_info = "data/model/qwen25/q_r_l20_remote_cache_tpsize_2.json",
            ),
            smoke_test(
                name = "remote_cache_pd",
                data = ["@remote_kv_cache_manager_server//:bin/kv_cache_manager_bin"],
                gpu_type = ["L20"],
                kvcm_envs = ["SEQ_SIZE_PER_BLOCK=8", "KVCM_LOG_LEVEL=DEBUG"],
                sleep_time_qr = 20,
                smoke_args = {
                    "prefill": "--warm_up 0  --reuse_cache 1 --role_type PREFILL --act_type FP16 --seq_size_per_block 8 --enable_remote_cache true --enable_device_cache 0 --deterministic_attn 1 --reco_put_timeout_ms 12000 --reco_get_timeout_ms 12000 --reco_get_broadcast_timeout 15000 --reco_put_broadcast_timeout 15000",
                    "decode": "--warm_up 0  --reuse_cache 1 --role_type DECODE --act_type FP16 --seq_size_per_block 8 --enable_remote_cache true --enable_device_cache 0 --deterministic_attn 1 --reco_put_timeout_ms 12000 --reco_get_timeout_ms 12000 --reco_get_broadcast_timeout 15000 --reco_put_broadcast_timeout 15000",
                },
                task_info = "data/model/qwen25/q_r_l20_remote_cache_pd_sep.json",
            ),
            smoke_test(
                name = "remote_cache_match_fail",
                data = ["@remote_kv_cache_manager_server//:bin/kv_cache_manager_bin"],
                gpu_type = ["L20"],
                kvcm_envs = ["SEQ_SIZE_PER_BLOCK=8", 
                    "KVCM_LOG_LEVEL=DEBUG",
                    "ENABLE_DEBUG_SERVICE=TRUE",
                    "TEST_MATCH_FAILURE=1",
                ],
                sleep_time_qr = 10,
                smoke_args = "--warm_up 0 --reuse_cache 1 --act_type FP16 --seq_size_per_block 8 --enable_remote_cache true --enable_device_cache 0",
                task_info = "data/model/qwen25/q_r_l20_remote_cache_match_failure.json",
            ),
            smoke_test(
                name = "remote_cache_write_start_fail",
                data = ["@remote_kv_cache_manager_server//:bin/kv_cache_manager_bin"],
                gpu_type = ["L20"],
                kvcm_envs = ["SEQ_SIZE_PER_BLOCK=8", 
                    "KVCM_LOG_LEVEL=DEBUG",
                    "ENABLE_DEBUG_SERVICE=TRUE",
                    "TEST_START_WRITE_FAILURE=1",
                ],
                sleep_time_qr = 10,
                smoke_args = "--warm_up 0 --reuse_cache 1 --act_type FP16 --seq_size_per_block 8 --enable_remote_cache true --enable_device_cache 0 --deterministic_attn 1",
                task_info = "data/model/qwen25/q_r_l20_remote_cache_start_and_finish_failure.json",
            ),
            smoke_test(
                name = "remote_cache_write_finish_fail",
                data = ["@remote_kv_cache_manager_server//:bin/kv_cache_manager_bin"],
                gpu_type = ["L20"],
                kvcm_envs = ["SEQ_SIZE_PER_BLOCK=8", 
                    "KVCM_LOG_LEVEL=DEBUG",
                    "ENABLE_DEBUG_SERVICE=TRUE",
                    "TEST_FINISH_WRITE_FAILURE=1",
                ],
                sleep_time_qr = 10,
                smoke_args = "--warm_up 0 --reuse_cache 1 --act_type FP16 --seq_size_per_block 8 --enable_remote_cache true --enable_device_cache 0 --deterministic_attn 1",
                task_info = "data/model/qwen25/q_r_l20_remote_cache_start_and_finish_failure.json",
            ),
            smoke_test(
                name = "remote_cache_edge",
                data = ["@remote_kv_cache_manager_server//:bin/kv_cache_manager_bin"],
                gpu_type = ["L20"],
                kvcm_envs = ["SEQ_SIZE_PER_BLOCK=4", "KVCM_LOG_LEVEL=DEBUG"],
                sleep_time_qr = 10,
                smoke_args = "--warm_up 0  --reuse_cache 1 --act_type FP16 --seq_size_per_block 4 --enable_remote_cache true --enable_device_cache 0",
                task_info = "data/model/qwen25/q_r_l20_cache_edge_case_1_remote_cache.json",
            ),
        ],
    )

