py_test(
    name = "multimodal_image_load_test",
    srcs = [
        "multimodal_image_load_test.py",
    ],
    deps = [
        "//maga_transformer:testlib",
    ],
    exec_properties = {'gpu':'A10'},
)
