KV_CACHE_EVENT_ENV_CASES = (
    (
        "KV_CACHE_EVENT_PUBLISHER_TYPE",
        "kv_cache_event_publisher_type",
        "kvcm",
        "kvcm",
    ),
    (
        "KV_CACHE_EVENT_MANAGER_ENDPOINT",
        "kv_cache_event_manager_endpoint",
        "http://kvcm-meta:56020",
        "http://kvcm-meta:56020",
    ),
    (
        "KV_CACHE_EVENT_INSTANCE_GROUP",
        "kv_cache_event_instance_group",
        "test-group",
        "test-group",
    ),
    (
        "KV_CACHE_EVENT_INSTANCE_ID",
        "kv_cache_event_instance_id",
        "test-instance",
        "test-instance",
    ),
    (
        "KV_CACHE_EVENT_HOST_IP_PORT",
        "kv_cache_event_host_ip_port",
        "127.0.0.1:18000",
        "127.0.0.1:18000",
    ),
    (
        "KV_CACHE_EVENT_QUEUE_CAPACITY",
        "kv_cache_event_queue_capacity",
        "12345",
        12345,
    ),
    (
        "KV_CACHE_EVENT_REPORT_BATCH_SIZE",
        "kv_cache_event_report_batch_size",
        "321",
        321,
    ),
    (
        "KV_CACHE_EVENT_FLUSH_INTERVAL_MS",
        "kv_cache_event_flush_interval_ms",
        "17",
        17,
    ),
    (
        "KV_CACHE_EVENT_HEARTBEAT_INTERVAL_MS",
        "kv_cache_event_heartbeat_interval_ms",
        "1017",
        1017,
    ),
    (
        "KV_CACHE_EVENT_REQUEST_TIMEOUT_MS",
        "kv_cache_event_request_timeout_ms",
        "1517",
        1517,
    ),
    (
        "KV_CACHE_EVENT_SNAPSHOT_TIMEOUT_MS",
        "kv_cache_event_snapshot_timeout_ms",
        "3017",
        3017,
    ),
    (
        "KV_CACHE_EVENT_RETRY_INTERVAL_MS",
        "kv_cache_event_retry_interval_ms",
        "517",
        517,
    ),
    (
        "KV_CACHE_EVENT_SNAPSHOT_INTERVAL_MS",
        "kv_cache_event_snapshot_interval_ms",
        "300017",
        300017,
    ),
    (
        "KV_CACHE_EVENT_LOG_MAX_KEYS",
        "kv_cache_event_log_max_keys",
        "13",
        13,
    ),
)

KV_CACHE_EVENT_FIELD_VALUES = {
    field_name: expected_value
    for _, field_name, _, expected_value in KV_CACHE_EVENT_ENV_CASES
}
