load("//:def.bzl", "copts")

cc_library(
    name = "handler_args",
    hdrs = [
        "HandlerArgs.h",
    ],
    srcs = [
        "HandlerArgs.cc",
    ],
    copts = copts(),
    visibility = ["//visibility:public"],
)

