load("//:def.bzl", "copts")

cc_library(
    name = "HandlerArgs",
    hdrs = [
        "HandlerArgs.h",
    ],
    srcs = [
        "HandlerArgs.cc",
    ],
    copts = copts(),
    deps = [],
    visibility = ["//visibility:public"],
)
