# create_grpc_proto.py
# Generate Python gRPC stubs for predict_v2 (and model_config). Same usage pattern as
# rtp_llm/cpp/model_rpc/proto/create_grpc_proto.py: run once to produce pb files; no runtime generation.
#
# Usage (from repo root):
#   python rtp_llm/bailian/proto/create_grpc_proto.py [output_dir]
# Default output_dir = this directory (rtp_llm/bailian/proto); generate_proto_py passes that path.
import os
import subprocess
import sys


def main():
    proto_dir = os.path.dirname(os.path.abspath(__file__))
    if len(sys.argv) >= 2:
        output_dir = os.path.abspath(sys.argv[1])
    else:
        output_dir = proto_dir
    os.makedirs(output_dir, exist_ok=True)

    cmd_base = [
        sys.executable,
        "-m",
        "grpc_tools.protoc",
        f"-I{proto_dir}",
        f"--python_out={output_dir}",
        f"--grpc_python_out={output_dir}",
    ]
    for name in ["model_config.proto", "predict_v2.proto"]:
        proto_file = os.path.join(proto_dir, name)
        subprocess.run(cmd_base + [proto_file], check=True)

    # Fix package-relative imports so "from rtp_llm.bailian.proto import ..." works.
    # protoc generates "import model_config_pb2" but we need "from . import model_config_pb2".
    for fname in ("predict_v2_pb2.py", "predict_v2_pb2_grpc.py"):
        path = os.path.join(output_dir, fname)
        if os.path.isfile(path):
            with open(path, "r") as f:
                text = f.read()
            text = text.replace(
                "import model_config_pb2", "from . import model_config_pb2"
            )
            text = text.replace("import predict_v2_pb2", "from . import predict_v2_pb2")
            with open(path, "w") as f:
                f.write(text)

    init_py = os.path.join(output_dir, "__init__.py")
    if not os.path.exists(init_py):
        with open(init_py, "w") as f:
            f.write("# Predict v2 Python stubs. Generated by create_grpc_proto.py\n")
    print("Generated Python protos in %s" % output_dir)


if __name__ == "__main__":
    main()
