#include "_v41_wo_a_quant.cuh"

#define sm100_fp8_fp4_gemm_1d1d_impl v41_wo_a_group32_epilogue
#include <deep_gemm/impls/sm100_fp8_fp4_gemm_1d1d.cuh>
#undef sm100_fp8_fp4_gemm_1d1d_impl

using namespace deep_gemm;

static void instantiate_v41_wo_a() {
    auto small = reinterpret_cast<void*>(&v41_wo_a_group32_epilogue<cute::UMMA::Major::K,
                                                                    cute::UMMA::Major::K,
                                                                    32,
                                                                    32,
                                                                    32,
                                                                    0,
                                                                    1024,
                                                                    4096,
                                                                    32,
                                                                    128,
                                                                    128,
                                                                    8,
                                                                    128,
                                                                    128,
                                                                    128,
                                                                    11,
                                                                    2,
                                                                    128,
                                                                    128,
                                                                    2,
                                                                    true,
                                                                    V41_NUM_SMS,
                                                                    true,
                                                                    true,
                                                                    GemmType::Batched,
                                                                    false,
                                                                    cutlass::float_e4m3_t,
                                                                    cutlass::float_e4m3_t,
                                                                    cutlass::float_e4m3_t,
                                                                    epilogue::transform::EpilogueDynamicScaledFP8>);
    auto large = reinterpret_cast<void*>(&v41_wo_a_group32_epilogue<cute::UMMA::Major::K,
                                                                    cute::UMMA::Major::K,
                                                                    32,
                                                                    32,
                                                                    32,
                                                                    0,
                                                                    1024,
                                                                    4096,
                                                                    128,
                                                                    256,
                                                                    128,
                                                                    8,
                                                                    128,
                                                                    128,
                                                                    128,
                                                                    5,
                                                                    2,
                                                                    128,
                                                                    128,
                                                                    2,
                                                                    false,
                                                                    V41_NUM_SMS,
                                                                    false,
                                                                    true,
                                                                    GemmType::Batched,
                                                                    false,
                                                                    cutlass::float_e4m3_t,
                                                                    cutlass::float_e4m3_t,
                                                                    cutlass::float_e4m3_t,
                                                                    epilogue::transform::EpilogueDynamicScaledFP8>);
}

using SmallStorage = layout::SM100FP8FP4GemmSharedStorage<11,
                                                          2,
                                                          2,
                                                          16,
                                                          128,
                                                          128,
                                                          16,
                                                          128,
                                                          128,
                                                          128,
                                                          1,
                                                          cutlass::float_e4m3_t,
                                                          cutlass::float_e4m3_t,
                                                          cutlass::float_e4m3_t>;
using LargeStorage = layout::SM100FP8FP4GemmSharedStorage<5,
                                                          2,
                                                          2,
                                                          128,
                                                          128,
                                                          128,
                                                          128,
                                                          128,
                                                          128,
                                                          256,
                                                          1,
                                                          cutlass::float_e4m3_t,
                                                          cutlass::float_e4m3_t,
                                                          cutlass::float_e4m3_t>;

extern "C" __device__ __constant__ unsigned v41_wo_a_metadata[5] = {
    sizeof(SmallStorage), sizeof(LargeStorage), V41_NUM_SMS, sizeof(EpilogueArgs), offsetof(EpilogueArgs, alpha)};
