cc_binary(
    name = "local_subscribe_service_main",
    srcs = [
        "LocalSubscribeServiceMain.cpp",
    ],
    deps = [
        "//maga_transformer/cpp/disaggregate/load_balancer/subscribe:subscribe",
    ],
    linkstatic = True,
)

cc_binary(
    name = "cm2_subscribe_service_main",
    srcs = [
        "CM2SubscribeServiceMain.cpp",
    ],
    deps = [
        "//maga_transformer/cpp/disaggregate/load_balancer/subscribe:subscribe",
    ],
    linkstatic = True,
)