py_test (
    name = "decoder_engine_test",
    srcs = ["decoder_engine_test.py"],
    data = [
        "//maga_transformer/test/model_test/fake_test/testdata:testdata",
    ],
    deps = [
        "//maga_transformer:models",
        "//maga_transformer:_ft_pickler",
        "//maga_transformer:config",
        "//maga_transformer:testlib",
        "//maga_transformer/test/model_test/test_util:test_util"
    ],
)

py_test (
    name = "async_model_test",
    srcs = ["async_model_test.py"],
    data = [
        "//maga_transformer/test/model_test/fake_test/testdata:testdata",
    ],
    deps = [
        "//maga_transformer:models",
        "//maga_transformer:_ft_pickler",
        "//maga_transformer:config",
        "//maga_transformer:testlib",
        "//maga_transformer/test/model_test/test_util:test_util"
    ],
)

py_test (
    name = "cache_manager_test",
    srcs = ["cache_manager_test.py"],
    data = [
        "//maga_transformer/test/model_test/fake_test/testdata:testdata",
    ],
    deps = [
        "//maga_transformer:models",
        "//maga_transformer:_ft_pickler",
        "//maga_transformer:config",
        "//maga_transformer:testlib",
        "//maga_transformer/test/model_test/test_util:test_util"
    ],
)

py_test (
    name = "scheduler_test",
    srcs = ["scheduler_test.py"],
    data = [
        "//maga_transformer/test/model_test/fake_test/testdata:testdata",
    ],
    deps = [
        "//maga_transformer:models",
        "//maga_transformer:_ft_pickler",
        "//maga_transformer:config",
        "//maga_transformer:testlib",
        "//maga_transformer/test/model_test/test_util:test_util"
    ],
)

py_test (
    name = "reuse_mask_test",
    srcs = ["reuse_mask_test.py"],
    deps = [
        "//maga_transformer:models",
        "//maga_transformer:_ft_pickler",
        "//maga_transformer:config",
        "//maga_transformer:testlib",
        "//maga_transformer/test/model_test/test_util:test_util"
    ],
)