package org.flexlb.mockengine;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertNotNull;

/**
 * Guards the stress-baseline master config against FlexlbConfig schema
 * drift: every master config and performance model pair must parse
 * against the current FlexlbConfig schema. MockPerformanceModel.load runs
 * ConfigService.parse with FAIL_ON_UNKNOWN_PROPERTIES, so any renamed or
 * removed field (e.g. the base switch renamed prefill outlierRejection
 * maxWaitVsAverageMultiplier to maxProjectedDrainVsAverageMultiplier)
 * surfaces here before a remote run wastes a full build.
 *
 * <p>The master document is generated by tools/online_eval/flexlb_cfg.py
 * (the FLEXLB_CONFIG SSOT); the snapshot below is the stress-na130 render
 * and is kept in lockstep by tools/online_eval/tests/test_flexlb_cfg.py
 * (byte-equal assertion), so a Python-side render change that breaks the
 * Java schema surfaces on either side.
 */
class ConfigSchemaGuardTest {

    private static final String[] MASTERS = {
            "src/test/resources/master-config-stress-na130.json",
    };

    private static final String[] PERFORMANCES = {
            "../tools/online_eval/data/performance/dsv4_flash_performance.fast_ab.json",
            "../tools/online_eval/data/performance/dsv4_flash_performance.sm100_dev.json",
    };

    @Test
    void shippedConfigPairsParseAgainstCurrentSchema() throws Exception {
        for (String master : MASTERS) {
            for (String performance : PERFORMANCES) {
                assertNotNull(MockPerformanceModel.load(performance, master),
                        master + " + " + performance + " must load");
            }
        }
    }
}
