package(default_visibility = ["//maga_transformer:__subpackages__", "//internal_source:__subpackages__"])

py_library(
    name = "loader",
    srcs = glob([
        "*.py",
    ]),
    deps = [
        "//maga_transformer:utils",
    ]
)