package(default_visibility = ["//visibility:public"])

py_library(
    name = "device_resource",
    deps = [],
    srcs = ["device_resource.py"],
)

py_library(
    name = "port_util",
    deps = [],
    srcs = ["port_util.py"],
)

py_test(
    name = "port_util_test",
    srcs = ["port_util_test.py"],
    deps = [
        ":port_util",
    ],
)
