py_library(
    name = "ascend_moe",
    srcs = glob(["*.py"]),
    deps = ["//rtp_llm/models_py/modules/factory/fused_moe/impl/ascend/strategy:ascend_strategies"],
    visibility = ["//visibility:public"],
)
