py_test(
    name = "test_bitmask_ops",
    srcs = [
        "test_bitmask_ops.py",
    ],
    data = [
        "//rtp_llm:sdk",
    ],
    deps = [
        "//rtp_llm:testlib",
    ],
    exec_properties = {"gpu": "H20"},
    tags = ["manual"],
)
