package org.flexlb.util;

import com.fasterxml.jackson.dataformat.cbor.CBORGenerator;
import org.junit.jupiter.api.Test;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HexFormat;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

class BlockCacheKeyCalculatorTest {

    private static final HexFormat HEX = HexFormat.of();
    // Generated by vLLM sha256_cbor with PYTHONHASHSEED=0.
    private static final String NONE_HASH =
            "4e1195df020de59e0d65a33a4279f1183e7ae4e5d980e309f8b55adff2e61c3e";

    @Test
    void encodesHashSeedExactlyLikeVllmCanonicalCbor() throws Exception {
        byte[] encodedSeed = encode(BlockCacheKeyCalculator::writeHashSeed);

        assertEquals("6130", HEX.formatHex(encodedSeed));
        assertEquals(NONE_HASH, sha256Hex(encodedSeed));
    }

    @Test
    void encodesCanonicalIntegerBoundariesExactlyLikeVllm() throws Exception {
        List<Long> inputIds = List.of(
                0L, 23L, 24L, 255L, 256L, 65535L, 65536L, 4294967296L);
        byte[] encodedBlock = encode(generator -> BlockCacheKeyCalculator.writeBlock(
                generator, HEX.parseHex(NONE_HASH), inputIds, 0, inputIds.size()));

        assertEquals(
                "8358204e1195df020de59e0d65a33a4279f1183e7ae4e5d980e309f8b55adff2e61c3e"
                        + "880017181818ff19010019ffff1a000100001b0000000100000000f6",
                HEX.formatHex(encodedBlock));
        assertEquals(
                "7c02b51a59661eef31aca6f060756646fcd0c78a3efb10527fc0bb435b80d5dd",
                sha256Hex(encodedBlock));
        assertEquals(
                List.of(9205563536317666781L),
                BlockCacheKeyCalculator.calculate(inputIds, inputIds.size()));
    }

    @Test
    void matchesVllmSingleBlockFullHashAndCacheKey() throws Exception {
        List<Long> inputIds = List.of(1L, 2L, 3L, 4L);
        byte[] blockHash = hashBlock(HEX.parseHex(NONE_HASH), inputIds, 0, 4);

        assertEquals(
                "c9d58ba695280d69b243e1e0df813136ca9196b286fb1a021e0b2e028ef071cb",
                HEX.formatHex(blockHash));
        assertEquals(
                List.of(2164874634404590027L),
                BlockCacheKeyCalculator.calculate(inputIds, 4));
    }

    @Test
    void matchesVllmChainedBlockFullHashesAndSignedCacheKeys() throws Exception {
        List<Long> inputIds = new ArrayList<>();
        for (long tokenId = 0; tokenId < 128; tokenId++) {
            inputIds.add(tokenId);
        }
        byte[] firstBlockHash = hashBlock(HEX.parseHex(NONE_HASH), inputIds, 0, 64);
        byte[] secondBlockHash = hashBlock(firstBlockHash, inputIds, 64, 64);

        assertEquals(
                "ddfc07d6c65195c803c8619358c7b0ae3aabee104d3bc6e59787c2001f45d77a",
                HEX.formatHex(firstBlockHash));
        assertEquals(
                "c61732f6553f8367340fd94d0d76c692b13f865bec1cf6b092e8bedefdf74b3e",
                HEX.formatHex(secondBlockHash));
        assertEquals(
                List.of(-7527834946346035334L, -7860823284622341314L),
                BlockCacheKeyCalculator.calculate(inputIds, 64));
    }

    @Test
    void dropsFinalPartialBlock() {
        List<Long> inputIds = new ArrayList<>();
        for (long tokenId = 0; tokenId < 130; tokenId++) {
            inputIds.add(tokenId);
        }

        assertEquals(
                List.of(-7527834946346035334L, -7860823284622341314L),
                BlockCacheKeyCalculator.calculate(inputIds, 64));
    }

    @Test
    void returnsEmptyListWhenThereIsNoCompleteBlock() {
        assertEquals(List.of(), BlockCacheKeyCalculator.calculate(List.of(1L, 2L), 4));
    }

    @Test
    void rejectsInvalidInput() {
        assertThrows(
                IllegalArgumentException.class,
                () -> BlockCacheKeyCalculator.calculate(null, 1));
        assertThrows(
                IllegalArgumentException.class,
                () -> BlockCacheKeyCalculator.calculate(List.of(1L), 0));
        assertThrows(
                IllegalArgumentException.class,
                () -> BlockCacheKeyCalculator.calculate(Arrays.asList(1L, null), 2));
    }

    private static byte[] hashBlock(
            byte[] parentHash,
            List<Long> inputIds,
            int tokenOffset,
            int blockSize) throws Exception {
        return MessageDigest.getInstance("SHA-256").digest(encode(generator ->
                BlockCacheKeyCalculator.writeBlock(
                        generator, parentHash, inputIds, tokenOffset, blockSize)));
    }

    private static String sha256Hex(byte[] value) throws NoSuchAlgorithmException {
        return HEX.formatHex(MessageDigest.getInstance("SHA-256").digest(value));
    }

    private static byte[] encode(CborWriter writer) throws IOException {
        ByteArrayOutputStream output = new ByteArrayOutputStream();
        try (CBORGenerator generator = BlockCacheKeyCalculator.newCborGenerator(output)) {
            writer.write(generator);
        }
        return output.toByteArray();
    }

    @FunctionalInterface
    private interface CborWriter {
        void write(CBORGenerator generator) throws IOException;
    }
}
