# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import kvcm_meta_service_pb2 as kvcm__meta__service__pb2


class MetaServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetClusterInfo = channel.unary_unary(
            "/kv_cache_manager.proto.meta.MetaService/GetClusterInfo",
            request_serializer=kvcm__meta__service__pb2.GetClusterInfoRequest.SerializeToString,
            response_deserializer=kvcm__meta__service__pb2.GetClusterInfoResponse.FromString,
        )
        self.GetHostCacheState = channel.unary_unary(
            "/kv_cache_manager.proto.meta.MetaService/GetHostCacheState",
            request_serializer=kvcm__meta__service__pb2.GetHostCacheStateRequest.SerializeToString,
            response_deserializer=kvcm__meta__service__pb2.GetHostCacheStateResponse.FromString,
        )


class MetaServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetClusterInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetHostCacheState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_MetaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetClusterInfo": grpc.unary_unary_rpc_method_handler(
            servicer.GetClusterInfo,
            request_deserializer=kvcm__meta__service__pb2.GetClusterInfoRequest.FromString,
            response_serializer=kvcm__meta__service__pb2.GetClusterInfoResponse.SerializeToString,
        ),
        "GetHostCacheState": grpc.unary_unary_rpc_method_handler(
            servicer.GetHostCacheState,
            request_deserializer=kvcm__meta__service__pb2.GetHostCacheStateRequest.FromString,
            response_serializer=kvcm__meta__service__pb2.GetHostCacheStateResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "kv_cache_manager.proto.meta.MetaService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class MetaService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetClusterInfo(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/kv_cache_manager.proto.meta.MetaService/GetClusterInfo",
            kvcm__meta__service__pb2.GetClusterInfoRequest.SerializeToString,
            kvcm__meta__service__pb2.GetClusterInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetHostCacheState(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/kv_cache_manager.proto.meta.MetaService/GetHostCacheState",
            kvcm__meta__service__pb2.GetHostCacheStateRequest.SerializeToString,
            kvcm__meta__service__pb2.GetHostCacheStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
