py_test(
    name = "validate_cuda13_runtime_test",
    srcs = [
        "validate_cuda13_runtime.py",
        "validate_cuda13_runtime_test.py",
    ],
    main = "validate_cuda13_runtime_test.py",
)
