

py_test(
    name = "gen_pyi",
    srcs = [
        "gen_pyi.py",
    ],
    deps = [
        "//rtp_llm:torch",
        "//rtp_llm:pybind11_stubgen",
        "//rtp_llm:rtp_llm_lib",
        "//rtp_llm:testlib",
    ],
    tags = [
        "manual",
    ],
)