py_library(
    name = "ascend_base",
    srcs = glob(["*.py"]),
    deps = [
        "//rtp_llm:torch",
        "//rtp_llm/models_py/distributed:collective_torch",
    ],
    visibility = ["//visibility:public"],
)
