py_library(
    name = "metrics",
    srcs = glob([
        "*.py"
    ]),
    visibility = ["//visibility:public"],
    deps = ["//maga_transformer/aios/kmonitor:kmonitor_py",
            "//maga_transformer/distribute:distribute"],
)
